fix: コメントアウトを外す

diff --git a/.github/workflows/ci-backend-for-all.yaml b/.github/workflows/ci-backend-for-all.yaml
--- a/.github/workflows/ci-backend-for-all.yaml
+++ b/.github/workflows/ci-backend-for-all.yaml
@@ -130,21 +130,21 @@ jobs:
       working-directory: .
       run: docker compose --file=docker-compose.ci.yaml up --build --detach mysql
 
-    # - name: Wait start MySQL
-    #   run: |
-    #     #!/bin/bash
-    #     retry=60
-    #     count=1
-    #     until mysqladmin ping -h${DB_HOST} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD}; do
-    #       echo 'mysql is unavailable - sleeping'
-    #       sleep 3
-    #       if [ $(expr $retry - $count) -le 0 ]; then
-    #         echo 'mysql is unavailable - throw error for timeout'
-    #         exit 1
-    #       fi
-    #       count=$(expr $count + 1)
-    #     done
-    #     echo 'mysql is up - executing command'
+    - name: Wait start MySQL
+      run: |
+        #!/bin/bash
+        retry=60
+        count=1
+        until mysqladmin ping -h${DB_HOST} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD}; do
+          echo 'mysql is unavailable - sleeping'
+          sleep 3
+          if [ $(expr $retry - $count) -le 0 ]; then
+            echo 'mysql is unavailable - throw error for timeout'
+            exit 1
+          fi
+          count=$(expr $count + 1)
+        done
+        echo 'mysql is up - executing command'
 
     - uses: actions/cache@v3
       id: modules-cache
